<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetExt>.gha</TargetExt>
    <TargetFramework>net48</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>DivideCentered</AssemblyName>
    <RootNamespace>DivideCentered</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="8.*" IncludeAssets="compile;build" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*" />
  </ItemGroup>
</Project>
